### ISSUE TITLE
openAIChat.streamTokens() doesn't stream the tokens when the response is a function_call (tool_call)

### ISSUE THREAD

**Issue by nichochar** [axflow/axflow#100]
A chunk from when getting a tool response looks like this:
```
      {
        id: 'chatcmpl-8LOwr2AcOfQU0zPGdCKkyYIlnz30B',
        object: 'chat.completion.chunk',
        created: 1700111481,
        model: 'gpt-4-1106-preview',
        system_fingerprint: 'fp_a24b4d720c',
        choices: [
          {
            index: 0,
            delta: {
              tool_calls: [ { index: 1, function: { arguments: ', Jap' } } ]
            },
            finish_reason: null
          }
        ]
      }
```

Our library doesn't expect the delta to be `tool_calls`, so returns an empty string.

here's another chunk, with the function name:
```
      {
        id: 'chatcmpl-8LOwr2AcOfQU0zPGdCKkyYIlnz30B',
        object: 'chat.completion.chunk',
        created: 1700111481,
        model: 'gpt-4-1106-preview',
        system_fingerprint: 'fp_a24b4d720c',
        choices: [
          {
            index: 0,
            delta: {
              tool_calls: [
                {
                  index: 2,
                  id: 'call_ucviJGsYAwobgBAMamh5mGb3',
                  type: 'function',
                  function: { name: 'get_current_weather', arguments: '' }
                }
              ]
            },
            finish_reason: null
          }
        ]
      }
```

**Comment by nichochar** [comment]
Types were fixed in https://github.com/axflow/axflow/pull/101, but we might need to do more to support tools in the accessors

**Comment by benjreinhart** [comment]
Yes, I would expect this to be the case, though I agree it's not well documented and therefore confusing.

`stream` streams the response as is from the underlying provider. `streamTokens` was meant to be a high-level wrapper that plucks out the message content. You could argue functions/tools are message content, but this considers message content to be the user-facing text output, not other objects in the response. Of the models supported in this library, only openai supports tools/functions. If you want to use those, `stream` is the appropriate method.
