### ISSUE TITLE
Is this repository runnable in Windows OS ?

### ISSUE THREAD

**Issue by DVGY** [axflow/axflow#85]
Is this repository runnable in Windows OS ? 

Can anyone answer this question to me ?

Thanks

**Comment by benjreinhart** [comment]
@DVGY I have not tested on windows, so I do not know for sure. However, I can't think of a reason why it wouldn't be. There are a few places that interact with the filesystem, but IIRC those make sure to use platform agnostic helpers, like `Path.join`. 

The models package in particular should be runnable as there are zero dependencies and no file system or operating system calls.

**Comment by benjreinhart** [comment]
You should give it a try and let us know if you run into issues!
